### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by perfect7gentleman**

### CODE REVIEW

**Comment by gcarq** [comment]
Chromium 53.0.2785.101 does not build with -Dsafe_browsing=0.
I updated the patch, but it needs more work: https://github.com/gcarq/inox-patchset/blob/feature/add-more-patches/fix-building-without-safebrowsing.patch

I will open an issue and create a seperate branch for this

**Comment by Eloston** [comment]
@gcarq: I'm currently running a test build of ungoogled-chromium 53.0.2785.101 with an updated version of it. [Here it is](https://github.com/Eloston/ungoogled-chromium/blob/master/resources/common/patches/ungoogled-chromium/fix-building-without-safebrowsing.patch). It's getting quite lengthy now...

I don't think it's related, but Developer Tools won't load in my current build. If you want to be sure, you can hold on for a bit longer until I tag a new release.

**Comment by gcarq** [comment]
@Eloston I released version 54.0.280.100 and updated your patch, it builds now with `safe_browsing_mode=0` [fix-building-without-safebrowsing.patch](https://github.com/gcarq/inox-patchset/blob/54.0.2840.100/fix-building-without-safebrowsing.patch)

Developer Tools are working fine for me with the latest version including this patch.

I'm closing this PR since its no longer relevant.

**Comment by Eloston** [comment]
@gcarq Devtools breaking was due to domain substitution; it had nothing to do with safe browsing. And thanks for including the patch in Inox!

I feel like Inox and ungoogled-chromium are slowly merging together...

**Pull request closed without merging**
