### PR TITLE
An extremely hardened branch

### PR DESCRIPTION
**Pull request by nyancat18**
what has

* the only useful and live iridium patch,  deletes cookies by default

* all @xsmile 's patches

* almost all @eloston 's  patches **i've only rejected patches that talks to iridium code, because apply this patches its a hell**

* some extra build flags

* hardened desktop files (using archwiki's info..lol)

### CODE REVIEW

**Comment by nyancat18** [comment]
*some extra* summary

* adds some desktop files, with hardenings from archwiki and installgentoo wiki, and some *useful* setups **out of the box**

* a new pkgbuild  **PKGBUILD.3**

**Comment by nyancat18** [comment]
updating for fix cve

**Comment by nyancat18** [comment]
updating to upstream

**Comment by csmk** [comment]
You need to improve your commit title/description.

You can't expect [this message](https://github.com/gcarq/inox-patchset/pull/98/commits/45b81bbc650707f4b645d3a746b51ea3dc718452#diff-dfa7cdd9c34798e1af82f172b0822f08R216) to pass, do you?!

**Comment by gcarq** [comment]
I won't merge this PR, because the commit messages are very confuse and it encourages usage with TOR/I2P. As already mentioned earlier I don't encourage usage with TOR/I2P because I cannot guarantee everything is patched accordingly, and also you are a unicorn if you don't use Tor Browser.
Additionally this PR is way to long, how I'm supposed to review PR with +18,599 additions?

**Pull request closed without merging**
