### PR TITLE
inox 57

### PR DESCRIPTION
**Pull request by triceratops1**
with it

we've a base
for inox57

sources:
some cleaning (search&replace/kill) and archlinux official commits, we can begin to work.

if you just need my changes

are at
https://u.teknik.io/ypxFU.7z

checksum: aceb216204a75c0fe5334d7b15586f2eb7f32864a94c662cc9d96d64eba3514db6750e60f10d4a32dd3a1b04b7949cb6a28127ed929ea7991e023026f6060560  ypxFU.7z

### CODE REVIEW

**Comment by triceratops1** [comment]
2 fixed patches
1 patch gapped (branding)

updtaed checksums, debug echo messages, blocked bad/redundant/unuserful patches

**Comment by triceratops1** [comment]
@perfect7gentleman @csmk

**Comment by perfect7gentleman** [comment]
@triceratops1, I'm  listening.

**Comment by triceratops1** [comment]
@perfect7gentleman can you help me to compile

my  inox57?


https://u.teknik.io/ypxFU.7z

checksum: aceb216204a75c0fe5334d7b15586f2eb7f32864a94c662cc9d96d64eba3514db6750e60f10d4a32dd3a1b04b7949cb6a28127ed929ea7991e023026f6060560 ypxFU.7z

or at my pull request :)

**Comment by triceratops1** [comment]
i got
this

at 32bit
[ 6606s] ../../chrome/browser/browsing_data/chrome_browsing_data_remover_delegate.cc:600:30: error: 'class BrowserProcess' has no member named 'safe_browsing_service'; did you mean 'metrics_service'?
[ 6606s]            g_browser_process->safe_browsing_service();
[ 6606s]                               ^~~~~~~~~~~~~~~~~~~~~
[ 6607s] [23118/25355] CXX obj/chrome/browser/browser/bookmark_stats.o
[ 6607s] [23119/25355] CXX obj/chrome/browser/browser/top_sites_factory.o
[ 6607s] [23120/25355] CXX obj/chrome/browser/browser/history_service_factory.o
[ 6608s] [23121/25355] CXX obj/chrome/browser/browser/history_tab_helper.o
[ 6608s] [23122/25355] CXX obj/chrome/browser/browser/managed_bookmark_service_factory.o
[ 6608s] [23123/25355] CXX obj/chrome/browser/browser/chrome_bookmark_client.o
[ 6609s] [23124/25355] CXX obj/chrome/browser/browser/bookmark_model_factory.o
[ 6609s] [23125/25355] CXX obj/chrome/browser/browser/web_history_service_factory.o
[ 6611s] [23126/25355] CXX obj/chrome/browser/browser/browsing_history_service.o
[ 6611s] ninja: build stopped: subcommand failed.

**Comment by csmk** [comment]
Yes?

**Comment by gcarq** [comment]
Please only open a PR if the commits have a meaningful and self-contained name and the changes are tested (or put a [WIP] tag). Sorry but this PR doesn't make any sense for me.

**Pull request closed without merging**
